[package]
name = "quicksilver_train"
version = "0.1.0"
authors = ["harmony <me@hrmny.pw>"]

[dependencies]
rand = { version = "0.7", features = ["stdweb"] }
quicksilver = {version = "0.3", default-features = false }

